### ISSUE TITLE
timeseries bucketing incorrect

### ISSUE THREAD

**Issue by cdbethune** [uncharted-distil/distil#1003]
The acled dataset provides daily timestamps, but when we render the different variables at 1 day resolution the facets and graph view seem to alternate valid counts with zero values:

![image](https://user-images.githubusercontent.com/8959554/58125322-4dd0da80-7bde-11e9-8226-20b06189a47e.png)

**Comment by GAO8A** [comment]
Upon investigating the network calls to creating a timeseries summary, it appears the categorized bucketing does match what the charts are displaying, a zero gap, every 3-4 day intervals.

![Screen Shot 2019-06-17 at 3 08 31 PM](https://user-images.githubusercontent.com/8060908/59640452-f6595800-9112-11e9-8225-9e2d860a6d22.png)

This applies for other feature calls like `country_iso_code` and `main_actor_types`

**Comment by GAO8A** [comment]
Fixed by https://github.com/uncharted-distil/distil/pull/1052
