### ISSUE TITLE
Add support for model ranking of features

### ISSUE THREAD

**Issue by cdbethune** [uncharted-distil/distil#1010]
While there's a path in the TA3TA2 API (see https://gitlab.com/datadrivendiscovery/ta3ta2-api/issues/111#note_158158837) to extract feature weights from a fitted model, it is somewhat awkward and likely wouldn't be well supported by TA2s.  We will extend our TA2 to write out a CSV file containing feature names and weights whenever they are available, using `<pipeline-id>-weights.csv` in the `D3MTEMPDIR` as the path.  The TA3 can parse the pipeline using the `Describe` function and check for the file if weights are flagged in a description step.  If the file isn't there, the system should gracefully continue without ranking information.

**Comment by phorne-uncharted** [comment]
add-explain-call is the branch for this issue.

So far, the describe solution call has been added after a fit. The pipeline description is then updated to call `produce_feature_importances` on flagged primitives and return the feature weights via output uri. 

Running with pipeline runner did not work as the suggested target field doesnt get updated to target and true target by the pipeline runner so an extract primitive fails.

Running with auto ml is failing with an unimplemented exception. I do not know where this exception is coming from as no logs are produced on the auto ml side but the error is coming from the grpc interceptor associated with auto ml. I also cannot find any reference to the execute pipeline call in the auto ml code.

**Comment by cdbethune** [comment]
Looks like this isn't working properly in auto ML right now - tracked under uncharted-distil/distil-auto-ml#30.
