### ISSUE TITLE
MI ranking fails when category change to City

### ISSUE THREAD

**Issue by cdbethune** [uncharted-distil/distil#1014]
Using the ACLED dataset, if you change the semantic type of Admin 3 to 'City' MI ranking fails - the suggestion panel just indicates there was an unexpected error.

**Comment by GAO8A** [comment]
Ranking seems to fail intermitently, regardless if geocoding is need (eg for City type) the container log is as following:
`0m Killed
[36melastic_1          |[0m Running elasticsearch
[33mrunner_1           |[0m DEBUG:d3m.namespace:Loading entry point 'data_transformation.dataset_to_dataframe.Common'.
[33mrunner_1           |[0m WARNING:d3m.namespace:While loading primitive 'data_transformation.dataset_to_dataframe.Common', an error has been detected: The 'xgboost==0.81' distribution was not found and is required by the application
[33mrunner_1           |[0m WARNING:d3m.namespace:Attempting to load primitive 'data_transformation.dataset_to_dataframe.Common' without checking requirements.
[33mrunner_1           |[0m DEBUG:git.cmd:Popen(['git', 'cat-file', '--batch-check'], cwd=/src/common-primitives, universal_newlines=False, shell=None)
[33mrunner_1           |[0m WARNING:d3m.metadata.pipeline:Name for primitive '4b42ce1e-9b98-4a25-b68e-fad13311eb65' does not match the one specified in the primitive description. Primitive description name: 'Dataset to DataFrame converter'. Resolved primitive name: 'Extract a DataFrame from a Dataset'.
[33mrunner_1           |[0m WARNING:d3m.metadata.pipeline:Digest for primitive '4b42ce1e-9b98-4a25-b68e-fad13311eb65' does not match the one specified in the primitive description. Primitive description digest: 85b946aa6123354fe51a288c3be56aaca82e76d4071c1edc13be6f9e0e100144. Resolved primitive digest: 564540b25e3af21df1bbcba2e8e8122e612ef97dcec65fde2ee488472500de83.
[33mrunner_1           |[0m DEBUG:d3m.namespace:Loading entry point 'data_transformation.column_parser.DataFrameCommon'.
[33mrunner_1           |[0m WARNING:d3m.namespace:While loading primitive 'data_transformation.column_parser.DataFrameCommon', an error has been detected: The 'xgboost==0.81' distribution was not found and is required by the application
[33mrunner_1           |[0m WARNING:d3m.namespace:Attempting to load primitive 'data_transformation.column_parser.DataFrameCommon' without checking requirements.
[33mrunner_1           |[0m DEBUG:git.cmd:Popen(['git', 'cat-file', '--batch-check'], cwd=/src/common-primitives, universal_newlines=False, shell=None)
[33mrunner_1           |[0m WARNING:d3m.metadata.pipeline:Version for primitive 'd510cb7a-1782-4f51-b44c-58f0236e47c7' does not match the one specified in the primitive description. Primitive description version: '0.4.0'. Resolved primitive version: '0.5.0'.
[33mrunner_1           |[0m DEBUG:d3m.namespace:Loading entry point 'feature_selection.mi_ranking.DistilMIRanking'.
[33mrunner_1           |[0m DEBUG:git.cmd:Popen(['git', 'cat-file', '--batch-check'], cwd=/src/distilmiranking, universal_newlines=False, shell=None)
[33mrunner_1           |[0m WARNING:d3m.metadata.base:d3m.primitives.feature_selection.mi_ranking.DistilMIRanking: Primitive's Python path does not adhere to d3m.primitives namespace specification. Reason: primitive family segment must match primitive's primitive family.
[33mrunner_1           |[0m WARNING:d3m.metadata.base:d3m.primitives.feature_selection.mi_ranking.DistilMIRanking: Primitive's Python path does not adhere to d3m.primitives namespace specification. Reason: must have a known primitive name segment.
[33mrunner_1           |[0m WARNING:d3m.metadata.pipeline:Version for primitive 'a31b0c26-cca8-4d54-95b9-886e23df8886' does not match the one specified in the primitive description. Primitive description version: '0.2.0'. Resolved primitive version: '0.2.1'.
[33mrunner_1           |[0m WARNING:d3m.metadata.pipeline:Digest for primitive 'a31b0c26-cca8-4d54-95b9-886e23df8886' does not match the one specified in the primitive description. Primitive description digest: 5302eebf2fb8a80e9f00e7b74888aba9eb448a9c0463d9d26786dab717a62c61. Resolved primitive digest: 4c2792a01a9c38752bf93dd5dd903d9c1c26c45d5a2085cee32db1074a95a0ef.
[33mrunner_1           |[0m ERROR:__main__:D3M dataset 'file:///Users/rgao/go/src/github.com/uncharted-distil/distil/datasets/LL0_acled_reduced_clean/TRAIN/datasetDoc.json' cannot be found.
[36melastic_1          |[0m [2019-06-10T16:43:17,431][INFO ][o.e.n.Node               ] [] initializing ...
[36melastic_1          |[0m [2019-06-10T16:43:18,092][INFO ][o.e.e.NodeEnvironment    ] [Yw4teEh] using [1] data paths, mounts [[/ (overlay)]], net usable_space [45.6gb], net total_space [58.4gb], spins? [possibly], types [overlay]
[36melastic_1          |[0m [2019-06-10T16:43:18,093][INFO ][o.e.e.NodeEnvironment    ] [Yw4teEh] heap size [1.9gb], compressed ordinary object pointers [true]
[36melastic_1          |[0m [2019-06-10T16:43:18,289][INFO ][o.e.n.Node               ] node name [Yw4teEh] derived from node ID [Yw4teEhwS0u5z8bSo_hXMw]; set [node.name] to override
[36melastic_1          |[0m [2019-06-10T16:43:18,289][INFO ][o.e.n.Node               ] version[5.4.3], pid[7], build[eed30a8/2017-06-22T00:34:03.743Z], OS[Linux/4.9.125-linuxkit/amd64], JVM[Oracle Corporation/OpenJDK 64-Bit Server VM/1.8.0_131/25.131-b11]
[36melastic_1          |[0m [2019-06-10T16:43:18,290][INFO ][o.e.n.Node               ] JVM arguments [-Xms2g, -Xmx2g, -XX:+UseConcMarkSweepGC, -XX:CMSInitiatingOccupancyFraction=75, -XX:+UseCMSInitiatingOccupancyOnly, -XX:+DisableExplicitGC, -XX:+AlwaysPreTouch, -Xss1m, -Djava.awt.headless=true, -Dfile.encoding=UTF-8, -Djna.nosys=true, -Djdk.io.permissionsUseCanonicalPath=true, -Dio.netty.noUnsafe=true, -Dio.netty.noKeySetOptimization=true, -Dio.netty.recycler.maxCapacityPerThread=0, -Dlog4j.shutdownHookEnabled=false, -Dlog4j2.disable.jmx=true, -Dlog4j.skipJansi=true, -XX:+HeapDumpOnOutOfMemoryError, -Des.path.home=/usr/share/elasticsearch]
[36melastic_1          |[0m [2019-06-10T16:43:22,331][INFO ][o.e.p.PluginsService     ] [Yw4teEh] loaded module [aggs-matrix-stats]
[36melastic_1          |[0m [2019-06-10T16:43:22,331][INFO ][o.e.p.PluginsService     ] [Yw4teEh] loaded module [ingest-common]
[36melastic_1          |[0m [2019-06-10T16:43:22,334][INFO ][o.e.p.PluginsService     ] [Yw4teEh] loaded module [lang-expression]
[36melastic_1          |[0m [2019-06-10T16:43:22,341][INFO ][o.e.p.PluginsService     ] [Yw4teEh] loaded module [lang-groovy]
[36melastic_1          |[0m [2019-06-10T16:43:22,341][INFO ][o.e.p.PluginsService     ] [Yw4teEh] loaded module [lang-mustache]
[36melastic_1          |[0m [2019-06-10T16:43:22,341][INFO ][o.e.p.PluginsService     ] [Yw4teEh] loaded module [lang-painless]
[36melastic_1          |[0m [2019-06-10T16:43:22,341][INFO ][o.e.p.PluginsService     ] [Yw4teEh] loaded module [percolator]
[36melastic_1          |[0m [2019-06-10T16:43:22,342][INFO ][o.e.p.PluginsService     ] [Yw4teEh] loaded module [reindex]
[36melastic_1          |[0m [2019-06-10T16:43:22,342][INFO ][o.e.p.PluginsService     ] [Yw4teEh] loaded module [transport-netty3]
[36melastic_1          |[0m [2019-06-10T16:43:22,342][INFO ][o.e.p.PluginsService     ] [Yw4teEh] loaded module [transport-netty4]
[36melastic_1          |[0m [2019-06-10T16:43:22,344][INFO ][o.e.p.PluginsService     ] [Yw4teEh] no plugins loaded
[36melastic_1          |[0m [2019-06-10T16:43:29,242][INFO ][o.e.d.DiscoveryModule    ] [Yw4teEh] using discovery type [zen]
[36melastic_1          |[0m [2019-06-10T16:43:30,764][INFO ][o.e.n.Node               ] initialized
[36melastic_1          |[0m [2019-06-10T16:43:30,766][INFO ][o.e.n.Node               ] [Yw4teEh] starting ...
[36melastic_1          |[0m [2019-06-10T16:43:31,290][INFO ][o.e.t.TransportService   ] [Yw4teEh] publish_address {127.0.0.1:9300}, bound_addresses {127.0.0.1:9300}
[36melastic_1          |[0m [2019-06-10T16:43:32,786][INFO ][o.e.m.j.JvmGcMonitorService] [Yw4teEh] [gc][2] overhead, spent [282ms] collecting in the last [1s]
[36melastic_1          |[0m [2019-06-10T16:43:34,483][INFO ][o.e.c.s.ClusterService   ] [Yw4teEh] new_master {Yw4teEh}{Yw4teEhwS0u5z8bSo_hXMw}{OAR4TUTNTOeG2x2NqUduMQ}{127.0.0.1}{127.0.0.1:9300}, reason: zen-disco-elected-as-master ([0] nodes joined)
[36melastic_1          |[0m [2019-06-10T16:43:34,541][INFO ][o.e.h.n.Netty4HttpServerTransport] [Yw4teEh] publish_address {172.17.0.5:9200}, bound_addresses {0.0.0.0:9200}
[36melastic_1          |[0m [2019-06-10T16:43:34,565][INFO ][o.e.n.Node               ] [Yw4teEh] started
[36melastic_1          |[0m [2019-06-10T16:43:34,808][WARN ][o.e.d.i.m.TypeParsers    ] field [include_in_all] is deprecated, as [_all] is deprecated, and will be disallowed in 6.0, use [copy_to] instead.
[36melastic_1          |[0m [2019-06-10T16:43:34,819][WARN ][o.e.d.i.m.TypeParsers    ] field [include_in_all] is deprecated, as [_all] is deprecated, and will be disallowed in 6.0, use [copy_to] instead.
[36melastic_1          |[0m [2019-06-10T16:43:35,109][INFO ][o.e.g.GatewayService     ] [Yw4teEh] recovered [1] indices into cluster_state
[36melastic_1          |[0m [2019-06-10T16:43:35,233][WARN ][o.e.d.i.m.TypeParsers    ] field [include_in_all] is deprecated, as [_all] is deprecated, and will be disallowed in 6.0, use [copy_to] instead.
[36melastic_1          |[0m [2019-06-10T16:43:35,235][WARN ][o.e.d.i.m.TypeParsers    ] field [include_in_all] is deprecated, as [_all] is deprecated, and will be disallowed in 6.0, use [copy_to] instead.
[36melastic_1          |[0m [2019-06-10T16:43:37,423][INFO ][o.e.c.r.a.AllocationService] [Yw4teEh] Cluster health status changed from [RED] to [YELLOW] (reason: [shards started [[datasets][0]] ...]).
[36melastic_1          |[0m [2019-06-10T16:48:31,746][INFO ][o.e.m.j.JvmGcMonitorService] [Yw4teEh] [gc][300] overhead, spent [484ms] collecting in the last [1s]
[33mrunner_1           |[0m Traceback (most recent call last):
[33mrunner_1           |[0m   File "/usr/local/lib/python3.6/dist-packages/d3m/container/dataset.py", line 402, in load
[33mrunner_1           |[0m     with open(dataset_doc_path, 'r', encoding='utf8') as dataset_doc_file:
[33mrunner_1           |[0m FileNotFoundError: [Errno 2] No such file or directory: '/Users/rgao/go/src/github.com/uncharted-distil/distil/datasets/LL0_acled_reduced_clean/TRAIN/datasetDoc.json'
[33mrunner_1           |[0m 
[33mrunner_1           |[0m The above exception was the direct cause of the following exception:
[33mrunner_1           |[0m 
[33mrunner_1           |[0m Traceback (most recent call last):
[33mrunner_1           |[0m   File "./pipelinerunner/server.py", line 53, in ExecutePipeline
[33mrunner_1           |[0m     static_res_path)
[33mrunner_1           |[0m   File "/pipelinerunner/pipeline_executor.py", line 99, in execute_pipeline
[33mrunner_1           |[0m     inputs = _load_inputs(dataset_filenames)
[33mrunner_1           |[0m   File "/pipelinerunner/pipeline_executor.py", line 52, in _load_inputs
[33mrunner_1           |[0m     input_dataset = container.Dataset.load(dataset_filename)
[33mrunner_1           |[0m   File "/usr/local/lib/python3.6/dist-packages/d3m/container/dataset.py", line 1513, in load
[33mrunner_1           |[0m     lazy=lazy, compute_digest=compute_digest, strict_digest=strict_digest, handle_score_split=handle_score_split,
[33mrunner_1           |[0m   File "/usr/local/lib/python3.6/dist-packages/d3m/container/dataset.py", line 407, in load
[33mrunner_1           |[0m     ) from error
[33mrunner_1           |[0m d3m.exceptions.DatasetNotFoundError: D3M dataset 'file:///Users/rgao/go/src/github.com/uncharted-distil/distil/datasets/LL0_acled_reduced_clean/TRAIN/datasetDoc.json' cannot be found.
[33mrunner_1           |[0m ERROR:grpc._server:Exception calling application: D3M dataset 'file:///Users/rgao/go/src/github.com/uncharted-distil/distil/datasets/LL0_acled_reduced_clean/TRAIN/datasetDoc.json' cannot be found.
[33mrunner_1           |[0m Traceback (most recent call last):
[33mrunner_1           |[0m   File "/usr/local/lib/python3.6/dist-packages/d3m/container/dataset.py", line 402, in load
[33mrunner_1           |[0m     with open(dataset_doc_path, 'r', encoding='utf8') as dataset_doc_file:
[33mrunner_1           |[0m FileNotFoundError: [Errno 2] No such file or directory: '/Users/rgao/go/src/github.com/uncharted-distil/distil/datasets/LL0_acled_reduced_clean/TRAIN/datasetDoc.json'
[33mrunner_1           |[0m 
[33mrunner_1           |[0m The above exception was the direct cause of the following exception:
[33mrunner_1           |[0m 
[33mrunner_1           |[0m Traceback (most recent call last):
[33mrunner_1           |[0m   File "/usr/local/lib/python3.6/dist-packages/grpc/_server.py", line 406, in _call_behavior
[33mrunner_1           |[0m     return behavior(argument, context), True
[33mrunner_1           |[0m   File "./pipelinerunner/server.py", line 66, in ExecutePipeline
[33mrunner_1           |[0m     raise ex
[33mrunner_1           |[0m   File "./pipelinerunner/server.py", line 53, in ExecutePipeline
[33mrunner_1           |[0m     static_res_path)
[33mrunner_1           |[0m   File "/pipelinerunner/pipeline_executor.py", line 99, in execute_pipeline
[33mrunner_1           |[0m     inputs = _load_inputs(dataset_filenames)
[33mrunner_1           |[0m   File "/pipelinerunner/pipeline_executor.py", line 52, in _load_inputs
[33mrunner_1           |[0m     input_dataset = container.Dataset.load(dataset_filename)
[33mrunner_1           |[0m   File "/usr/local/lib/python3.6/dist-packages/d3m/container/dataset.py", line 1513, in load
[33mrunner_1           |[0m     lazy=lazy, compute_digest=compute_digest, strict_digest=strict_digest, handle_score_split=handle_score_split,
[33mrunner_1           |[0m   File "/usr/local/lib/python3.6/dist-packages/d3m/container/dataset.py", line 407, in load
[33mrunner_1           |[0m     ) from error
[33mrunner_1           |[0m d3m.exceptions.DatasetNotFoundError: D3M dataset 'file:///Users/rgao/go/src/github.com/uncharted-distil/distil/datasets/LL0_acled_reduced_clean/TRAIN/datasetDoc.json' cannot be found.
[33mrunner_1           |[0m INFO:__main__:Starting gRPC server
[33mrunner_1           |[0m INFO:__main__:Received execute request: 
[33mrunner_1           |[0m pipelineDescription {
[33mrunner_1           |[0m   context: TESTING
[33mrunner_1           |[0m   name: "roger"
[33mrunner_1           |[0m   inputs {
[33mrunner_1           |[0m     name: "input 0"
[33mrunner_1           |[0m   }
[33mrunner_1           |[0m   outputs {
[33mrunner_1           |[0m     name: "outputs 3"
[33mrunner_1           |[0m     data: "steps.3.produce"
[33mrunner_1           |[0m   }
[33mrunner_1           |[0m   steps {
[33mrunner_1           |[0m     primitive {
[33mrunner_1           |[0m       primitive {
[33mrunner_1           |[0m         id: "f31f8c1f-d1c5-43e5-a4b2-2ae4a761ef2e"
[33mrunner_1           |[0m         version: "0.2.0"
[33mrunner_1           |[0m         python_path: "d3m.primitives.data_transformation.denormalize.Common"
[33mrunner_1           |[0m         name: "Denormalize datasets"
[33mrunner_1           |[0m         digest: "c39e3436373aed1944edbbc9b1cf24af5c71919d73bf0bb545cba0b685812df1"
[33mrunner_1           |[0m       }
[33mrunner_1           |[0m       arguments {
[33mrunner_1           |[0m         key: "inputs"
[33mrunner_1           |[0m         value {
[33mrunner_1           |[0m           container {
[33mrunner_1           |[0m             data: "inputs.0"
[33mrunner_1           |[0m           }
[33mrunner_1           |[0m         }
[33mrunner_1           |[0m       }
[33mrunner_1           |[0m       outputs {
[33mrunner_1           |[0m         id: "produce"
[33mrunner_1           |[0m       }
[33mrunner_1           |[0m     }
[33mrunner_1           |[0m   }
[33mrunner_1           |[0m   steps {
[33mrunner_1           |[0m     primitive {
[33mrunner_1           |[0m       primitive {
[33mrunner_1           |[0m         id: "4b42ce1e-9b98-4a25-b68e-fad13311eb65"
[33mrunner_1           |[0m         version: "0.3.0"
[33mrunner_1           |[0m         python_path: "d3m.primitives.data_transformation.dataset_to_dataframe.Common"
[33mrunner_1           |[0m         name: "Dataset to DataFrame converter"
[33mrunner_1           |[0m         digest: "85b946aa6123354fe51a288c3be56aaca82e76d4071c1edc13be6f9e0e100144"
[33mrunner_1           |[0m       }
[33mrunner_1           |[0m       arguments {
[33mrunner_1           |[0m         key: "inputs"
[33mrunner_1           |[0m         value {
[33mrunner_1           |[0m           container {
[33mrunner_1           |[0m             data: "steps.0.produce"
[33mrunner_1           |[0m           }
[33mrunner_1           |[0m         }
[33mrunner_1           |[0m       }
[33mrunner_1           |[0m       outputs {
[33mrunner_1           |[0m         id: "produce"
[33mrunner_1           |[0m       }
[33mrunner_1           |[0m     }
[33mrunner_1           |[0m   }
[33mrunner_1           |[0m   steps {
[33mrunner_1           |[0m     primitive {
[33mrunner_1           |[0m       primitive {
[33mrunner_1           |[0m         id: "d510cb7a-1782-4f51-b44c-58f0236e47c7"
[33mrunner_1           |[0m         version: "0.4.0"
[33mrunner_1           |[0m         python_path: "d3m.primitives.data_transformation.column_parser.DataFrameCommon"
[33mrunner_1           |[0m         name: "Parses strings into their types"
[33mrunner_1           |[0m       }
[33mrunner_1           |[0m       arguments {
[33mrunner_1           |[0m         key: "inputs"
[33mrunner_1           |[0m         value {
[33mrunner_1           |[0m           container {
[33mrunner_1           |[0m             data: "steps.1.produce"
[33mrunner_1           |[0m           }
[33mrunner_1           |[0m         }
[33mrunner_1           |[0m       }
[33mrunner_1           |[0m       outputs {
[33mrunner_1           |[0m         id: "produce"
[33mrunner_1           |[0m       }
[33mrunner_1           |[0m     }
[33mrunner_1           |[0m   }
[33mrunner_1           |[0m   steps {
[33mrunner_1           |[0m     primitive {
[33mrunner_1           |[0m       primitive {
[33mrunner_1           |[0m         id: "a31b0c26-cca8-4d54-95b9-886e23df8886"
[33mrunner_1           |[0m         version: "0.2.0"
[33mrunner_1           |[0m         python_path: "d3m.primitives.feature_selection.mi_ranking.DistilMIRanking"
[33mrunner_1           |[0m         name: "Mutual Information Feature Ranking"
[33mrunner_1           |[0m         digest: "5302eebf2fb8a80e9f00e7b74888aba9eb448a9c0463d9d26786dab717a62c61"
[33mrunner_1           |[0m       }
[33mrunner_1           |[0m       arguments {
[33mrunner_1           |[0m         key: "inputs"
[33mrunner_1           |[0m         value {
[33mrunner_1           |[0m           container {
[33mrunner_1           |[0m             data: "steps.2.produce"
[33mrunner_1           |[0m           }
[33mrunner_1           |[0m         }
[33mrunner_1           |[0m       }
[33mrunner_1           |[0m       outputs {
[33mrunner_1           |[0m         id: "produce"
[33mrunner_1           |[0m       }
[33mrunner_1           |[0m       hyperparams {
[33mrunner_1           |[0m         key: "target_col_index"
[33mrunner_1           |[0m         value {
[33mrunner_1           |[0m           value {
[33mrunner_1           |[0m             data {
[33mrunner_1           |[0m               raw {
[33mrunner_1           |[0m                 int64: 8
[33mrunner_1           |[0m               }
[33mrunner_1           |[0m             }
[33mrunner_1           |[0m           }
[33mrunner_1           |[0m         }
[33mrunner_1           |[0m       }
[33mrunner_1           |[0m     }
[33mrunner_1           |[0m   }
[33mrunner_1           |[0m }
[33mrunner_1           |[0m inputs {
[33mrunner_1           |[0m   dataset_uri: "file:///Users/rgao/go/src/github.com/uncharted-distil/distil/datasets/196_autoMpg/TRAIN/dataset_TRAIN/datasetDoc.json"
[33mrunner_1           |[0m }
[33mrunner_1           |[0m 
[33mrunner_1           |[0m DEBUG:d3m.namespace:Loading entry point 'data_transformation.denormalize.Common'.
[33mrunner_1           |[0m WARNING:d3m.namespace:While loading primitive 'data_transformation.denormalize.Common', an error has been detected: The 'xgboost==0.81' distribution was not found and is required by the application
[33mrunner_1           |[0m WARNING:d3m.namespace:Attempting to load primitive 'data_transformation.denormalize.Common' without checking requirements.
[33mrunner_1           |[0m DEBUG:git.cmd:Popen(['git', 'cat-file', '--batch-check'], cwd=/src/common-primitives, universal_newlines=False, shell=None)
[33mrunner_1           |[0m WARNING:d3m.metadata.pipeline:Digest for primitive 'f31f8c1f-d1c5-43e5-a4b2-2ae4a761ef2e' does not match the one specified in the primitive description. Primitive description digest: c39e3436373aed1944edbbc9b1cf24af5c71919d73bf0bb545cba0b685812df1. Resolved primitive digest: 3afe339a3283f03a028dfecdfc94267585be6b5c48200d90af04b66a4afb95ce.
[33mrunner_1           |[0m DEBUG:d3m.namespace:Loading entry point 'data_transformation.dataset_to_dataframe.Common'.
[33mrunner_1           |[0m WARNING:d3m.namespace:While loading primitive 'data_transformation.dataset_to_dataframe.Common', an error has been detected: The 'xgboost==0.81' distribution was not found and is required by the application
[33mrunner_1           |[0m WARNING:d3m.namespace:Attempting to load primitive 'data_transformation.dataset_to_dataframe.Common' without checking requirements.
[33mrunner_1           |[0m DEBUG:git.cmd:Popen(['git', 'cat-file', '--batch-check'], cwd=/src/common-primitives, universal_newlines=False, shell=None)
[33mrunner_1           |[0m WARNING:d3m.metadata.pipeline:Name for primitive '4b42ce1e-9b98-4a25-b68e-fad13311eb65' does not match the one specified in the primitive description. Primitive description name: 'Dataset to DataFrame converter'. Resolved primitive name: 'Extract a DataFrame from a Dataset'.
[33mrunner_1           |[0m WARNING:d3m.metadata.pipeline:Digest for primitive '4b42ce1e-9b98-4a25-b68e-fad13311eb65' does not match the one specified in the primitive description. Primitive description digest: 85b946aa6123354fe51a288c3be56aaca82e76d4071c1edc13be6f9e0e100144. Resolved primitive digest: 564540b25e3af21df1bbcba2e8e8122e612ef97dcec65fde2ee488472500de83.
[33mrunner_1           |[0m DEBUG:d3m.namespace:Loading entry point 'data_transformation.column_parser.DataFrameCommon'.
[33mrunner_1           |[0m WARNING:d3m.namespace:While loading primitive 'data_transformation.column_parser.DataFrameCommon', an error has been detected: The 'xgboost==0.81' distribution was not found and is required by the application
[33mrunner_1           |[0m WARNING:d3m.namespace:Attempting to load primitive 'data_transformation.column_parser.DataFrameCommon' without checking requirements.
[33mrunner_1           |[0m DEBUG:git.cmd:Popen(['git', 'cat-file', '--batch-check'], cwd=/src/common-primitives, universal_newlines=False, shell=None)
[33mrunner_1           |[0m WARNING:d3m.metadata.pipeline:Version for primitive 'd510cb7a-1782-4f51-b44c-58f0236e47c7' does not match the one specified in the primitive description. Primitive description version: '0.4.0'. Resolved primitive version: '0.5.0'.
[33mrunner_1           |[0m DEBUG:d3m.namespace:Loading entry point 'feature_selection.mi_ranking.DistilMIRanking'.
[33mrunner_1           |[0m DEBUG:git.cmd:Popen(['git', 'cat-file', '--batch-check'], cwd=/src/distilmiranking, universal_newlines=False, shell=None)
[33mrunner_1           |[0m WARNING:d3m.metadata.base:d3m.primitives.feature_selection.mi_ranking.DistilMIRanking: Primitive's Python path does not adhere to d3m.primitives namespace specification. Reason: primitive family segment must match primitive's primitive family.
[33mrunner_1           |[0m WARNING:d3m.metadata.base:d3m.primitives.feature_selection.mi_ranking.DistilMIRanking: Primitive's Python path does not adhere to d3m.primitives namespace specification. Reason: must have a known primitive name segment.
[33mrunner_1           |[0m WARNING:d3m.metadata.pipeline:Version for primitive 'a31b0c26-cca8-4d54-95b9-886e23df8886' does not match the one specified in the primitive description. Primitive description version: '0.2.0'. Resolved primitive version: '0.2.1'.
[33mrunner_1           |[0m WARNING:d3m.metadata.pipeline:Digest for primitive 'a31b0c26-cca8-4d54-95b9-886e23df8886' does not match the one specified in the primitive description. Primitive description digest: 5302eebf2fb8a80e9f00e7b74888aba9eb448a9c0463d9d26786dab717a62c61. Resolved primitive digest: 4c2792a01a9c38752bf93dd5dd903d9c1c26c45d5a2085cee32db1074a95a0ef.
[33mrunner_1           |[0m WARNING:d3m.metadata.pipeline_run:'worker_id' was generated using the MAC address inside Docker container and is not a reliable compute resource identifier.
[33mrunner_1           |[0m WARNING:d3m.metadata.pipeline_run:Docker image environment variable not set: D3M_BASE_IMAGE_NAME
[33mrunner_1           |[0m WARNING:d3m.metadata.pipeline_run:Docker image environment variable not set: D3M_BASE_IMAGE_DIGEST
[33mrunner_1           |[0m WARNING:d3m.metadata.pipeline_run:Docker image environment variable not set: D3M_IMAGE_NAME
[33mrunner_1           |[0m WARNING:d3m.metadata.pipeline_run:Docker image environment variable not set: D3M_IMAGE_DIGEST`

**Comment by cdbethune** [comment]
Can no longer reproduce in latest version.
