### ISSUE TITLE
Data augmentation sets required different input dir

### ISSUE THREAD

**Issue by cdbethune** [uncharted-distil/distil#1023]
If you try and work with the imported data augmentation sets model runs will fail - we typically pass the `seed_datasets_current` dir as the dataset dir on startup, and we would need to pass `seed_datasets_data_augmentation` in order to build models against them.  This isn't really a problem for evals since use a specific set, but it would be an issue for demos.

**Comment by phorne-uncharted** [comment]
Potential approaches to resolve this issue:
symlinks to have the aug datasets mapped to the current datasets folder
copy all datasets to a tertiary folder and use that folder as root
