### ISSUE TITLE
Add finer grained binning intervals

### ISSUE THREAD

**Issue by cdbethune** [uncharted-distil/distil#1024]
UI currently supports Monthly and Weekly binning intervals.  We should support years, days, hours, minutes and should only display those that make sense for the span and frequency of the selected time data.

**Comment by cdbethune** [comment]
I would suggest taking this as far as adding support on the client side, and possibly extending the route on the server to handle the new args.  Going further requires changes to the DB that may need to be handed off.

**Comment by GAO8A** [comment]
Deemed unnecessary after reviewing existing binning of time intervals
