### ISSUE TITLE
Add timeseries clustering to asynch panel

### ISSUE THREAD

**Issue by cdbethune** [uncharted-distil/distil#1075]
When we successfully complete timeseries grouping we should kick off the sloth pipeline to cluster the results.  When complete, the user should be notified in via the asynch events panel, and applying the clustering should result in the timeseries facets displaying the clustered time series.

**Comment by phorne-uncharted** [comment]
There is now a clustering route in the backend that will call sloth given a dataset and variable `"/distil/cluster/:dataset/:variable"`. Due to how sloth is currently implemented, the variable name is not currently being used.
