### ISSUE TITLE
Join commit screen too narrow

### ISSUE THREAD

**Issue by cdbethune** [uncharted-distil/distil#1082]
The join preview screen is now about half as wide as it used to be.  

![image](https://user-images.githubusercontent.com/8959554/60731342-53c41600-9f15-11e9-9e52-d9938ff9b4ba.png)

**Comment by karlolsonuc** [comment]
initial investigation shows this is an issue with bootstrap's css, going to see if there's either a slightly different modal definition we should be using from bootstrap, or if we have to try to fight their definition with our own.

**Comment by karlolsonuc** [comment]
And here's a PR with the fix: https://github.com/uncharted-distil/distil/pull/1091 just needed to leverage the bootstrap vue API/attributes for modals correctly.
