### ISSUE TITLE
Progress Feedback on Import

### ISSUE THREAD

**Issue by phorne-uncharted** [uncharted-distil/distil#1140]
The user does not receive enough feedback when importing & joining a dataset. Given that some of these can go for quite a while (10+ minutes), the system should at least have a spinner to indicate that something is being run. Ideally some sort of progress bar or status label would also be present to provide feedback, but that may be a bit too much for now.

**Comment by GAO8A** [comment]
Fixed by https://github.com/uncharted-distil/distil/pull/1144
