### ISSUE TITLE
Remove import from join workflow

### ISSUE THREAD

**Issue by cdbethune** [uncharted-distil/distil#1151]
The import step is not required in the current data augmentation workflow.  We send the original dataset and the keywords to the search call, and then pass the search resluts and the dataset to the augment call.  At no time do we need to retrieve the dataset in order to run the join.  Removing this step will (hopefully) allow us to join with some of the larger datamart datasets, since the joined dataset will be no bigger than the original.

**Comment by cdbethune** [comment]
Note that a filter was added to hide join search results that were bigger than 100K rows to avoid lengthy import times.  With the import step removed, the filter can be removed as well.

**Comment by karlolsonuc** [comment]
Changes merged back.
