### ISSUE TITLE
Geocoordinate facet improvements

### ISSUE THREAD

**Issue by GAO8A** [uncharted-distil/distil#1171]
- Add type change menu to facet
- Add Mock explode for sub-facets
- Fix facet appearing on dataset change

**Comment by cdbethune** [comment]
A few other immediate items:

- Map should be contained in a card with a title and an icon, similar to other facets
- If we support pan/zoom then we should be recomputing the heatmap after each viewpoint change
- For ACLED dataset, heatmap data doesn't match map view data - there should be hits in Saudi Arabia/Yemen
