### ISSUE TITLE
Re-add timeseries normalization to pre-processing pipeline

### ISSUE THREAD

**Issue by cdbethune** [uncharted-distil/distil#1190]
The common primitives CSV reader was not properly dealing with nested timeseries data, which meant that we could not properly apply the flatten primitive to it, which in turn meant that we could not add support for pipeline prepend operations such as filters.  As it stands, prepends are disabled for timeseries problems.  

We should:
1. Fix the CSV reader, at least to the extent that it can support our use case
1. Re-enable the preprend for timeseries

**Comment by phorne-uncharted** [comment]
The CSV reader is currently not usable for our purposes. When the `return_result` hyper param is set to `replace`, it will instead return a dataframe with the whole contents replaced with whatever is loaded from CSV. 

In an exchange with Mitar, it became apparent that the current implementation may be as designed. It is unclear exactly how it could be updated to work for our use case.

```
mitar 11:39 AM
see "isCollection": true,
because of that, "columns" refer to internal structure of referenced CSV files
not to what the file collection resources is
so the embedded DataFrames in cells will have "columns"
phorne 11:41 AM
I get that part, but I dont get how you get that there is only 1 input column
is it because of the data resource set on line 16?
mitar 11:42 AM
there is only 1 input column for file collection because that is how file collections are represented in Dataset
this has nothing with the schema in datasetDoc.json
this is how dataset loader loads datasets which have a file collection
file collection is a directory on disk
all files in that directory
that is represented as a tabular resource with one column with the list of filenames in that directory
phorne 11:43 AM
interesting
mitar 11:43 AM
that is an artifical resource representing the file collection
phorne 11:43 AM
so youre saying that if I called denorm, then this primitive it should do the simple replace?
and have 3 output columns
mitar 11:44 AM
in both cases it will do a simple replace

no, it will not have 3 output columns
because it will replace that one column with one column where contents of each cell will have a table with 2 columns
you can then flatten that further to get one table
if this is what you want
(there should be a primitive for that in common primitives)
```

**Comment by cdbethune** [comment]
I will add timeseries formatter to `distil-primitives` and use that moving forward since it does what we want.  I'll update the pipelines to use that rather than the nested read and flatten.
