### ISSUE TITLE
Re-enable image regression workflow

### ISSUE THREAD

**Issue by cdbethune** [uncharted-distil/distil#1191]
We have some support for image regression in place, but never got it fully up and running due to a lack of TA2 systems that could handle the problem type.  We should be able to get it running end to end now.

**Comment by karlolsonuc** [comment]
findings:
- against mocks regression works for images predicting numerics
- need to block attempted use of images as the target facet, to be handle in PR shortly
- against auto ml on local regression fails and on staging it hangs, but likely due to the same missing tensorflow info.

**Comment by karlolsonuc** [comment]
Blocking attempts on image as target variable refined as part of this commit: https://github.com/uncharted-distil/distil/commit/fb87a25a2973d91eab363ae3635b1c3b0bbe2134
