### ISSUE TITLE
GeoFacet highlight support

### ISSUE THREAD

**Issue by cdbethune** [uncharted-distil/distil#1211]
When a facet in the system has a category or range selected, that range is broadcast to the rest of the system so that each facet can render records that match that selected range/category.  Rendering is done drawing the original baseline histogram in grey, and overlaying matches as a blue highlight.  The GeoFacet needs to respond in a similar fashion, rendering the highlight records using the existing colour ramp, and possibly the baseline set in gray.  It may be difficult to make that gray visible in a meaningful way, so we'll likely need to get input from a designer.

**Comment by GAO8A** [comment]
Fixed by #1228
