### ISSUE TITLE
GeoFacet range selection

### ISSUE THREAD

**Issue by cdbethune** [uncharted-distil/distil#1212]
Existing numerical facets allow for users to define a highlight range by clicking on the facet and dragging on min/max handles.  The GeoFacets should allow analog functionality, where clicking an dragging on the facet will create a rectangular selection region (this works now that we are not allowing pan/zoom of the geofacet).  This funcionality is already present in the map view and can mostly be copied from there.  The one notable difference is that the map view allows pan/zoom, so the selection requires a mode in that case.

**Comment by GAO8A** [comment]
Fixed by #1228
