### ISSUE TITLE
Geocoordinate variable requires its own type properties

### ISSUE THREAD

**Issue by GAO8A** [uncharted-distil/distil#1305]
When the geocoordinate variable is created, it appears to be of same type as the `longitude` variable it was formed with.

The list of variables fetched from the `distil/variables/${dataset}` end point will contain geocoordinate displayed like this:
![Screen Shot 2019-11-04 at 12 57 24 PM](https://user-images.githubusercontent.com/8060908/68159184-2492d500-ff06-11e9-82d0-a82423b9ee45.png)

Geocoordinate should have its own unique identifiable properties.

**Comment by cdbethune** [comment]
The type in the object field can be keyed off of for now.
