### ISSUE TITLE
Display ta2 version string in app landing page

### ISSUE THREAD

**Issue by cdbethune** [uncharted-distil/distil#1342]
We currently display distil version/build info at the bottom of the home screen.  We should add the version info we retrieve from the TA2 via the `hello` message to that string.

**Comment by YohannParis** [comment]
I will need to modify `distil-compute` as well to return the `version` number:
https://github.com/uncharted-distil/distil-compute/blob/master/primitive/compute/client.go#L178

Is that ok?

**Comment by cdbethune** [comment]
Yup.  That will require some go module updates, which @phorne-uncharted or I can help you with.

**Comment by YohannParis** [comment]
Ok, so I will pause this one for now, until I'm more familiar with the code, I'm already working on another issue.
