### ISSUE TITLE
Forecasting workflow

### ISSUE THREAD

**Issue by cdbethune** [uncharted-distil/distil#1370]
We currently rely on the D3M problem specification to provide us with information about the forecast start time and number of intervals, rather than allowing the user to set them.  A model is then trained using that fixed forecast period and the ground truth data, and displayed to the user in the result screen.  We need to develop a workflow that allows the user to set the forecasting horizon themselves in some capacity.   

This could be done on the create screen, and the result screen would allow the user to view the forecasted values, along with error information you can calculate by pushing your entire data period through the model.  No explicit "ineference" step would be needed in this case.

Alternatively, we could leave the horizon controls out of create, display the data the forecasting model generates along with the ground truth in the result screen, and then provide a "forecast" button that would then allow the user to set the horizon, and generate the forecast to be displayed in the following forecast exploration page (analogous to the flow from #1369).  

The latter seems like its forcing unnecessary steps into the process, but it is consistent to what would have to happen for classification/regression.

@slangevi @djonker - thoughts?

**Comment by YohannParis** [comment]
Update the **Apply Model** on Timeseries to **Forecast**:
- Change the button label accordingly.
- Remove the CSV upload modal box with a **Forecast Horizon** dialogue box where the user can select an interval size and number of them.
- The **interval size** input should depend on the Timeseries type; for Integer, the user can select an integer value,  for DateTime, the user can choose from a list (Yearly, Monthly, Weekly, etc.) based on the data format.
