### ISSUE TITLE
Validate datamart connectivity

### ISSUE THREAD

**Issue by cdbethune** [uncharted-distil/distil#1373]
We need to go through our data aug workflow and make sure it is still functional.

**Comment by phorne-uncharted** [comment]
Distil can search and join using the NYU datamart.

Distil can search using the ISI datamart.

The join suggestions from the ISI datamart point to invalid columns (they point to columns that are used by ISI for the join). Until that changes, Distil will not be able to join to datasets from the ISI datamart.

**Comment by phorne-uncharted** [comment]
NYU import works again (had to force version number). ISI still has issues with joins.
