### ISSUE TITLE
Analytic pipeline results should cache

### ISSUE THREAD

**Issue by cdbethune** [uncharted-distil/distil#1491]
Clustering, ranking, results  currently don't cache in any way on the server side.  On the client we track state in a particular client session via the route, but when a new client connects, we recalculate unnecessarily.  We should be able to build a cache key based on the inputs to particular call, and save the results under that key for future client requests.

**Comment by phorne-uncharted** [comment]
Initial implementation works in memory only. It will be updated to store to disk.

**Comment by phorne-uncharted** [comment]
PR #1516 fixed this issue.
