### ISSUE TITLE
Image facet empty when clusters not available

### ISSUE THREAD

**Issue by cdbethune** [uncharted-distil/distil#1523]
With a fresh database (ie. run `docker system prune && docker volume prune`) and a fresh output dir (remove the contents of your `$D3MOUTPUTDIR`) select the coil-20 or merced dataset.  On the target selection screen, the image facet will initially be set to `Text` (should be addressed separately).  Once it is set to type `Image` clustering will start to run in the background.  Until the clustering completes, the image facet  shows a stand in that contains some random image samples.  RIght now its coming up blank.

![image](https://user-images.githubusercontent.com/8959554/78043549-7c146000-7341-11ea-8cb1-ae71d943c65b.png)

**Comment by karlolsonuc** [comment]
Fixed by the changes in #1571 - closed.
