### ISSUE TITLE
Async analytic states needs to survive refresh

### ISSUE THREAD

**Issue by cdbethune** [uncharted-distil/distil#1525]
We indicate that background analytics like clustering or ranking have been updated by displaying a red dot over them.  When the user applies the update the red dot clears and the change is applied.  Currently there are two issues with state when you refresh the browser:
1. In the clustering case, the the red dot for clustering will re-appear, even though clustering has previously been applied.
2. In the ranking case, the red dot re-appears, and the variables are no longer displayed with rankings applied.

**Comment by YohannParis** [comment]
@cdbethune I'm having some trouble to figure out how to save those state.
We used `localStorage` API at `COMPASS`, also I cannot find an API endpoint to `distil-auto-ml` to save rankings or something of the sort.

Any guidance would be helpful.
