### ISSUE TITLE
Failed Geocoding of Variable Can Lead To Unrecoverable Error in API

### ISSUE THREAD

**Issue by karlolsonuc** [uncharted-distil/distil#1529]
Repro steps:
1.  Open Baseball Dataset
2.  Set Players to Address Type
3.  Reload
4.  Notice 500 in console of browser and the following issue in the API logs:
`[ ERROR ] no min / max aggregation values found
github.com/uncharted-distil/distil/api/model/storage/postgres.(*Storage).parseExtrema
        /Users/kolson/go/src/github.com/uncharted-distil/distil/api/model/storage/postgres/variable.go:48`

So we either need to have a more elegant recovery so that the dataset can return despite the 500 error allowing the user to change the data type back, or when geocoding fails, we need to revert to the previous type and notify the user that geocoding failed.

**Comment by phorne-uncharted** [comment]
I have so far been unable to reproduce this issue. I think this may happen if the geocoding fails due to not having the required static file.
