### ISSUE TITLE
Handle cases where column is empty

### ISSUE THREAD

**Issue by cdbethune** [uncharted-distil/distil#1557]
It is possible to encounter datasets where a column exists in the metadata, but is completely empty in the dataset itself.  This is most likely encountered when importing from CSV, where we need to read the CSV header row to get basic column information.  An easy reproduction case is to create a model for the `196_autoMpg` dataset using `class` as the target, then select the model and then use `TEST/dataset_TEST/tables/learningData.csv` as the prediction file.   The file contains a header for `class` but no actual data for it.

**Comment by phorne-uncharted** [comment]
I am pretty sure this was fixed a long time ago. I am unable to reproduce this problem right now.
