### ISSUE TITLE
No scroll bars on image tile view 

### ISSUE THREAD

**Issue by cdbethune** [uncharted-distil/distil#1570]
Images are rendering outside the container rather than displaying scroll bars.

![image](https://user-images.githubusercontent.com/8959554/79582173-691bc280-8099-11ea-921a-b48fa1ce3faa.png)

**Comment by YohannParis** [comment]
@cdbethune can you tell me which dataset you are using and where I can download it.

**Comment by YohannParis** [comment]
Fixed by @karlolsonuc directly on `master`.
