### ISSUE TITLE
Adding categorical feature to timeseries should update grouping

### ISSUE THREAD

**Issue by cdbethune** [uncharted-distil/distil#1610]
For something like the spawn dataset, we can create a timeseries using a single grouping ID, like `sector`, and `sector` will be automatically added as a selected feature.  `species` is still available as feature and can be added to the model.  When this happens, we should automatically update the grouping key of the timeseries to include both `species` and `sector`, otherwise, inclusion of the `sector` is meaningless.  The other option is to hide other non-numerical variables at that point, since it only makes sense to include additional timeseries.

**Comment by YohannParis** [comment]
Check with the TA2 server if a model is in `Forecasting` mode, then if the user want to add another `categorical` feature. We should offer the user to edit the Timeseries grouping.
