### ISSUE TITLE
Support D3M remote sensing datasets

### ISSUE THREAD

**Issue by cdbethune** [uncharted-distil/distil#1657]
MITLL gave us access to 2 seed datasets for remote sensing.  We need to make sure we can support ingesting working with the these.

**Comment by phorne-uncharted** [comment]
The eurosat dataset is a single multiband image file, with all the data being in the standard format (media folder has images, dataLearning.csv has the pointers to the files). Functionality has been added to split multiband images into separate files (1 / band) on user ingest. However, there is still no support for ingesting the multiband images from the seed datasets directly.
