### ISSUE TITLE
Add clustering to remote sensing

### ISSUE THREAD

**Issue by cdbethune** [uncharted-distil/distil#1664]
Remote sensing does not support clustering.  We need to add a pipeline that uses the remote sensing featurizer and clusters in the same way we do for images.

**Comment by phorne-uncharted** [comment]
There is now backend support for remote sensing clustering. The same clustering route needs to be called (`/distil/cluster/:dataset/:variable`), passing in the group variable as clustering var (`group_id_group` by default).

**Comment by cdbethune** [comment]
Still needs front end integration.
