### ISSUE TITLE
Use HDBSCAN for clustering

### ISSUE THREAD

**Issue by cdbethune** [uncharted-distil/distil#1665]
We currently use k-means based clustering for images.  We should use HDBSCAN since it will attempt to find an optimal set of clusters for the data, rather than forcing the clusters to a fixed count.  There are parameters to control min cluster size, so we should be able to avoid situations where we end up with a large number of small clusters.

**Comment by phorne-uncharted** [comment]
Updated the image clustering pipeline to use HDBSCAN, but defaulted the hyperparameters. It may be beneficial to look into a better approach for some of them.
