### ISSUE TITLE
ta3 reconnect to ta2

### ISSUE THREAD

**Issue by cdbethune** [uncharted-distil/distil#1679]
If the ta2 is restarted, the ta3 should reconnect.  It currently doesn't respond to the disconnect and has to be manually restarted.  GRPC should include some means to notify disconnections without having to resort to some sort of a manual heartbeat message.

**Comment by phorne-uncharted** [comment]
I tried to reproduce and things seem fairly stable in the end. Whenever I killed the TA2 server, the current processing would fail, but when I restarted the TA2 server I could create new models without problem.

**Comment by cdbethune** [comment]
Verified similar behaviour.  There are still probably some edge cases that cause the connection to drop, but nothing on the main path, which is what I saw previously and was worried about.
