### ISSUE TITLE
Remote Sensing Facet in Results

### ISSUE THREAD

**Issue by phorne-uncharted** [uncharted-distil/distil#1686]
The remote sensing facet does not display properly on the result page. It may not be detecting the correct kind of grouping and may be trying to display some other type of facet. No server side requests fail.

**Comment by cdbethune** [comment]
Looks like its a missing implementation:

https://github.com/unchartedsoftware/distil/blob/0a2a7dc3bbac4dee45d9099a0a89afb26bfd75ad/api/model/storage/postgres/remote_sensing.go#L249
