### ISSUE TITLE
Enforce min size tile represenation in map view

### ISSUE THREAD

**Issue by cdbethune** [uncharted-distil/distil#1708]
When zoomed out the remote sensing tile representation can be hard to see:

![image](https://user-images.githubusercontent.com/8959554/86361914-83018600-bc42-11ea-934e-9cea16fd19f0.png)

We should enforce some minimum size of the visual representation.  Leaflet probably has an API call to let you transform between geographic and pixel coordinates, but if not, you can derive the pixel size of the bounding box based on the tile zoom level.  That will let you figure out if you've crossed some minimum visual pixel size threshold at your current zoom level, and then render the bounding box at some minimum size to ensure it's visible.

**Comment by YohannParis** [comment]
Good idea.
I was thinking of making big dot (circle) has a click surface if the remote-sensing area is too small to see/click.
Having a different shape (circle instead of rectangle) might avoid confusion on what's happening.

What do you think?
