### ISSUE TITLE
Exploding Timeseries made of only Dates and Values (no grouping/series id) results in new extra column

### ISSUE THREAD

**Issue by karlolsonuc** [uncharted-distil/distil#1757]
Reproduction Steps

- open sunspots data set
- navigate to variable grouping view for timeseries creation from any facet
- group with year as time column and sunspots as value column
- submit the new grouping
- explode the newly created facet
- note the following new unknown/text type:

![Screen Shot 2020-07-14 at 12 29 30 PM](https://user-images.githubusercontent.com/51097558/87468115-d8884c00-c5cd-11ea-92d2-8ee26d8b4cf5.png)

There's probably a back end issue with how explode works in this use case vs. when we have at least grouping / series id column, and it's not an issue with geocoordinates which are always only two columns.

**Comment by cdbethune** [comment]
This should get cleaned up as part of #1421.
