### ISSUE TITLE
Available Datasets

### ISSUE THREAD

**Issue by phorne-uncharted** [uncharted-distil/distil#1799]
The import endpoint supports imports from the server filesystem by providing a path. There is also an endpoint to list available datasets in the augmented subfolder (excludes already ingested datasets). The client should be updated to let the user see what could be imported and then pass the selected file to the import endpoint.

`GET /distil/available` is the endpoint to list available datasets
`POST /distil/import/:datasetID/:source/:provenance` is the endpoint to import data (specifying the path parameter in the supplied json)

**Comment by cdbethune** [comment]
We should have the import button provide a means to select an import from a local file, or an import from a dataset on the server.  The server option should list the datasets returned by the next end point and start the import from there.
