### ISSUE TITLE
More guard rails on timeseries creation

### ISSUE THREAD

**Issue by cdbethune** [uncharted-distil/distil#1839]
The timeseries creation step overall is a bit un-intuitive, so anything we can add to keep the user on track is helpful.  A couple of things that seem to be relatively easy to handle:

1. In the group build screen, only show the series ID selection if there are text/categorical columns available.
1. In the group build screen, if the there is a single date column, pre-populate the date field with it.
1. In the group build screen, if there is only a single value left unselected that could be used for either time or value fields, automatically select them.
1. If the user clicks the timeseries button (in target select) or attempts to launch through the drop down, we should catch cases where there do not appear to be enough columns of the correct type to set value and time, and indicate that they may need to adjust data types to ensure the they numeric/date values for time available, and at least one value available.

**Comment by karlolsonuc** [comment]
After discussion with @cdbethune 2 & 3 aren't desirable behavior because users would have to cancel out of the view if the mis-select something and then can only clear it by cancelling the combination. However, the other changes are useful.
