### ISSUE TITLE
SHAP subset

### ISSUE THREAD

**Issue by cdbethune** [uncharted-distil/distil#1878]
Right now we do our train / test split, and then use the test data for scoring, as well as for producing predictions for the user to explore.  That same data is also fed into SHAP.  Given that SHAP can take quite a while to run, it is limited to 1500 rows of data by the SHAP primitive by default.  If we have more test data than 1500 rows, a large amount of our test data will be missing SHAP values which can lead to user confusion (and also limits the utility of computing the values in the first place).  A better solution would be to use the test subset for scoring, and then use a subset of test for the predictions we run SHAP against.  That will ensure that all the predictions we show the user have associated SHAP values.  

A second improvement would be to run SHAP as a seperate call.  We currently roll it into the sequence of messages for the overall train/score/produce flow, but we should be able to return the pipeline scores and test predictions to the user without SHAP values having been computed.   We can run them as a follow on step, and update the UI when its complete.

**Comment by phorne-uncharted** [comment]
The separate call for SHAP is dependent on an update to the core library which will add support for the `expose_outputs` field of the produce call. Once that change is in, then we can have the main produce call output the predictions and create a second produce call to run SHAP (and other explain produce functions) on a smaller subset.
