### ISSUE TITLE
Add a badge to show when a model has explanations available

### ISSUE THREAD

**Issue by cdbethune** [uncharted-distil/distil#1879]
We should add a badge next to the score for a model that indicates whether or not it has explanations available.  Currently we just don't show SHAP colouring, and swap the MI ranking values in for the missing feature importances.

**Comment by karlolsonuc** [comment]
To Do Back-end:
- Update result solution return to include new explanations field which will return an array of strings (representing an enumerated explanation type with `SHAP`, `WEIGHTS` & `MI`.)

To Do Front-end:
- Parse new explanation information in the return, use it to set new "Explanation" badge visibility.
