### ISSUE TITLE
Allow filtering by clusters

### ISSUE THREAD

**Issue by cdbethune** [uncharted-distil/distil#1886]
We currently display clusters in the UI, but if they are added to a filter, we will ignore them when the pipeilne is constructed.  This happens because the clustering operations are not added to the prepend, which means their data is not present when the TA2 is building the model.  A major use case for this would be to allow for certain types of remote sensing data to be filtered out, such as those clustered together due to the presence of clouds.

**Comment by phorne-uncharted** [comment]
A previous PR addressed this issue. Note that if we start treating filters more as parts of a filter set, then we will need to revisit how we filter clusters (and all prefiltering).
