### ISSUE TITLE
numRows from dataset not accurate

### ISSUE THREAD

**Issue by YohannParis** [uncharted-distil/distil#1894]
Using **ACLED** dataset, the response from the server for `distil/data/` returns the wrong value of `numRows`.

In the screenshot you can see that there are 4660 available values, but the back-end returns 12.

![Screen Shot 2020-08-21 at 15 15 06](https://user-images.githubusercontent.com/636801/90926444-1fcddd80-e3c1-11ea-82b7-6399fbd57c76.png)

**Comment by phorne-uncharted** [comment]
The bad count is caused by creating a grouping in the dataset but not having that grouping as target (ex: timeseries for fatalities while having event type as target). The fix is to handle groupings as intended as coved by #1421.
