### ISSUE TITLE
Large table view renders very slowly

### ISSUE THREAD

**Issue by cdbethune** [uncharted-distil/distil#1901]
Using ACLED and the setting the table to display 2000 items when all features are being modelled causes the system to lock up for  10 - 20 seconds evertime the table content is changed (for instance, by selecting a category through a facet).  Profiling shows all of this time being spent in the bootstrap-vue table control `render` function.

**Comment by karlolsonuc** [comment]
Further exploration: Even though we've removed the fixed-header-table component (and it's per-cell resizes/style setting,) rendering over ~100000 cells seems to stress even a recent mac book pro with an i7, taking ~30 seconds after the API data has loaded to display the table, at which point the table is responsive. Then, any action that could change the tables state such as filtering, sorting also takes ~30 seconds. 

Options to resolve this are adding pagination or adding some skeleton/virtual scrolling. Pagination could be handled by existing vue-bootstrap library components, while virtual scrolling might require leveraging an outside library such as https://github.com/Akryum/vue-virtual-scroller.

**Comment by cdbethune** [comment]
Virtual scrolling would certainly be a nicer user experience, so maybe start off by assessing how easy it would be to get one of the virtual scrolling libraries integrated.  If its not going to a straightforward, we can go with the table paging provided by the bootstrap table component.

**Comment by karlolsonuc** [comment]
@cdbethune looking at the various vue virtual scrolling solutions, none of them seem to rapidly integrate off hand with b-table from Bootstrap-Vue library, or at the very least, it's not as brisk as adding pagination, though I'd want to check there to make sure highlighting, sorting and filtering worked as expected as there could be gotchas.

**Comment by karlolsonuc** [comment]
So, even with pagination, add/removing highlights takes much longer with more rows. It looks like a considerable part of our performance trouble with large tables is that even with that pagination added, we are currently doing a search against every row in the tableData for the row highlight info to map back to facets, even for facets not currently in the table and thus definitely not highlight-able (thankfully it doesn't do the look up for undisplayed facets!) That was okay with 100 rows, but terrible with thousands of rows, as that search happens in computed properties, so it blocks re-rendering until it's finished for every facet visible, and it kicks off tons of garbage collection events during these searches, making everything even slower. We can't use the narrowed-down, paginated data to pre-narrow the search either as some one may select a row, then go to the next page, and the select another row as part of data curation, which needs to be reflected in the selected facets. However, we should be able drop that search from something every facet displayed does, to something that's done on once on change/load that's retrievable from the store by the facets or the subselection util function directly, and only when the facet actually has a row highlight to reflect. This also should have us looking at any/all areas where we do calculations or searches right before render as they'll continue to be pain points with larger data sets.
