### ISSUE TITLE
Fixed Header Table auto width caculation can bug

### ISSUE THREAD

**Issue by YohannParis** [uncharted-distil/distil#1909]
Because the component recalculates the header and cell width at each change of values, could be hundreds of times, the width can get messed up.

The following screenshot: the component calculates the mean's width to be 50px, but it gives the leftover space to the last column. When the Sparkline chart is rendered, the component keeps the mean column reference's excess size.

![Screen Shot 2020-09-03 at 11 47 31](https://user-images.githubusercontent.com/636801/92137799-9adcbe00-eddb-11ea-92a9-842f05fa815d.png)

**Comment by cdbethune** [comment]
Fixed by #1880
