### ISSUE TITLE
Exclusion facets should be black

### ISSUE THREAD

**Issue by cdbethune** [uncharted-distil/distil#1910]
Below we are showing "Exclusions" data (see tab).  The facets are displayed in blue - black should be used instead.

![image](https://user-images.githubusercontent.com/8959554/92166861-5d8e2580-ee07-11ea-90c7-4aa50242cbbf.png)

**Comment by karlolsonuc** [comment]
After talking this over with @Zac-hills yesterday, I took a pass at it since it's an area I'm familiar with, and since seeing how working with the facet3 library's gotchas in a PR could be valuable for showing how the code base works.
