### ISSUE TITLE
Infinitely growing flex boxes on FireFox

### ISSUE THREAD

**Issue by Zac-hills** [uncharted-distil/distil#2015]
This bug is on the result view screen. Initially it was believed that the webgl map was causing it. After some debugging and code checking the map is no longer in question. Another, indicator that it is an issue with the flex box is the other columns in the result view are infinitely scrolling.
![Peek 2020-10-26 14-24](https://user-images.githubusercontent.com/25306965/97213249-bdfe6b00-1797-11eb-9f0e-9ba194ede70f.gif)

**Comment by cdbethune** [comment]
Was this is a problem fixed in a subsequent firefox update?

**Comment by Zac-hills** [comment]
Just checked it is still infinitely scrolling. Mozzilla Firfox version 84.01.

**Comment by cdbethune** [comment]
Now an issue with chrome 89+ in Linux.
