### ISSUE TITLE
Lexbar assessment

### ISSUE THREAD

**Issue by cdbethune** [uncharted-distil/distil#2033]
We need to understand the work required to implement the lexbar feature that's used in World Modellers and F2.  There is an internal framework that is used (https://github.com/unchartedsoftware/lex) that would be a good place to start.

**Comment by YohannParis** [comment]
I have access to ASKE, a spin of World Modelers that use TypeScript and Vue.js, to see their recent implementations.
I look feasible, but with some fair amount of work on the way or filters work.

Most of the ASKE implementation can be used (Vue.js wrappers and VueX TypeScript modules), but it will be a drastic amount of cleaning on our end.

In a way, this would be an excellent time to deal with some technical debt by using already made tools.
