### ISSUE TITLE
Protoype implementation of data explorer

### ISSUE THREAD

**Issue by cdbethune** [uncharted-distil/distil#2045]
Start prototyping move to single data explorer screen in line with target design.  It would be best if we could bring it up as a separate view and build in parallel with the existing code base, eventually switching the app over to that view when we feel its ready.  There are still some points in the provided design that need to be refined, but this will at least let us start assessing the impact and provide a platform to test out different approaches.

**Comment by YohannParis** [comment]
Could you please share a screenshot of the slide for that view?
