### ISSUE TITLE
Add LexBar to application

### ISSUE THREAD

**Issue by cdbethune** [uncharted-distil/distil#2075]
Follow on to #2033.  We need to translate our current highlighting functionality to work with the lexbar now that we've got an idea of how it all works, and references to other projects in the company that are using it.  Synch up with @YohannParis to get a dump from him on what he found.  First step will be to plan how we want to go about introducing it into the system, as it is a pretty major change that will probably take a while to implement.

**Comment by YohannParis** [comment]
@karlolsonuc and I had a long talk about what I learn from _LexBar_ and how it can be implemented.
It can be resumed to:
- Beefing up the backend to send more information about _variables_ details
- Creating a wrapper around the external _LexBar_ library in Vue.js
- Keep using our current Store filtering model 
- Creating a utility to translate our current filtering model to _LexBar_ query language

**Comment by YohannParis** [comment]
I have access to _World Modeler_, and its spin-off written in Typescript _ASKE_, codebases; so we do not have to start completely from scratch.

**Comment by karlolsonuc** [comment]
The work can probably be broken up as follows:
1. Three public utility functions in a new util/lex.ts file: One that turns the list of variables into a Lex Bar language; one that turns the highlight/filter from our API into a Lex Bar query; and another that turns a Lex Bar query into our existing highlight/filter. These may have supporting private functions for any reused patterns and helpers, some of which may be similar to the state function wrappers from world modellers.
2. Component wrapper with props for a Lex Bar language & and a lex query, and that has an onChange bind that ties to onQueryChanged events in the Lex Bar. The function passed to onChange bind will leverage the Lex Bar query-to-highlight/filter utility function, then pass the result of that to the existing filter/highlight mutation/update functions.
3. Replacing the existing tag bar in each of the components that call it with the Lex Bar component
4. Any styling we want to show the difference between filters and highlights like we had before in the new Lex Bar.

**Comment by karlolsonuc** [comment]
Possible aside on 2. - we might want to see how much duplication there is in consuming the generic lex bar wrapper. If there's a lot, it could be worth building an intermediate wrapper that does all of the utility calls and takes in the distil formatted information (variables & filters) such that the consuming components and the lex bar component don't have to care about that for maximum reusability without code duplication.

**Comment by cdbethune** [comment]
I think we can close this one off, and track any updates/bugs as new issues.
