### ISSUE TITLE
Add date/timestamp based data splitting

### ISSUE THREAD

**Issue by cdbethune** [uncharted-distil/distil#2099]
We currently allow the user to specify the train/test split using a count/percentage based slide.  We should also enable a mode that allows the user to specify a date/timestamp as the split point, if either field type is available in the data.  Given that there may be multiple variables with an assigned type of date or timestamp, UI would have to support selection of the variable to use.

**Comment by phorne-uncharted** [comment]
The backend now supports this via a property on the solution request called `TimestampSplitValue` which has the float value of the timestamp to use for splitting. It would need to be added on the client and passed to the server in the solution request websocket call with a property called `timestampSplitValue`.

**Comment by cdbethune** [comment]
UI work is now being tracked separately under #2133.
