### ISSUE TITLE
Parquet column reader fails with high column datasets

### ISSUE THREAD

**Issue by venkatkorapaty** [uncharted-distil/distil#2113]
in `ReadData` for `parquet.go`, because each time parquet reads a column, it opens a new file header. This leads to reaching the `ulimit -n` and throwing an error such as:
[ ERROR ] open /Users/vkorapaty/data/output/augmented/big-earth-tiny_10-featurized/tables/learningData.parquet: too many open files
unable to read parquet file column index 22461
This was from trying to open a prefeaturised dataset with 32775 columns.

We need a good long term solution to deal with this.

**Comment by phorne-uncharted** [comment]
A fix was put in that works good enough for now. We would need to either change parquet library or fork it to update how the column reading is done to limit how many files are opened at any given time.
