### ISSUE TITLE
Support results containing rank values

### ISSUE THREAD

**Issue by cdbethune** [uncharted-distil/distil#2119]
The D3M result specification now allows for ta2 systems to return explicit rank columns in addition to the confidences and scores.  The TA3 should parse the rank column if present, store the results, and allow them to be forwarded to the client for rendering.

**Comment by phorne-uncharted** [comment]
Ranks are stored in the database alongside the confidence values, and returned to the client in a similar fashion. The call to the result endpoint will return `{"value":"no_hoppers","confidence":0.99738,"rank":59}` for the prediction output if rank is contained in the TA2 output.
