### ISSUE TITLE
Geo facet update time too long on large datasets

### ISSUE THREAD

**Issue by cdbethune** [uncharted-distil/distil#2140]
The heatmap view of the data presented by the geofacet does not scale well.  In working with the `locust-medium` dataset, which is about 17K tiles, it would take minutes for it to display the first time.  It seems like the time is spent entirely in the DB query given that running `top` during this time shows postgres processes eating up most of the CPU.  We may need to place an upper limit on the number of samples used in the heatmap query to speed things up.

**Comment by cdbethune** [comment]
I put together a prototype fix to this that uses a quad tree to store the tile bounds, and then runs `n * n` bucket queries to find the counts.  It requires a full fetch of the tile data from the DB to feed the query, which seems to account for most of the execution time - the population and query of the quadtree happens in < 10ms for an 11K tile dataset, with the DB fetch taking ~1s.  It looks like creating an index for the table based on the geocoords column may give us enough of a speed-up that we don't need to rely on this approach, but we know it will can scale if we run into problems with even larger sets.

**Comment by phorne-uncharted** [comment]
A previous PR added indices on remote sensing ingest and added a baseline filter on the band field to reduce the counts to tiles only rather than bands. Taken together, the summary endpoint takes well under a second for complete execution on the 11k tile dataset.
