### ISSUE TITLE
Extend Variable End Point to Return Categories & Update Lex Bar Grammar

### ISSUE THREAD

**Issue by karlolsonuc** [uncharted-distil/distil#2203]
Follow on for #2075 
- [x] Populate an optional categories field in the distil variables returned from the `/variables` end point (and so in the store and typescript interface) with the categories for categorical type variables with information from where ever that is in the DB.
- [x] Consume that categories field in the lex.ts utils such that the autocomplete/suggestions for categoricals can be leveraged to make lex filter/highlight building for those variables easier.

**Comment by cdbethune** [comment]
#2215 was merged, so you should be good to do the categorical portion of this work now.
