### ISSUE TITLE
Move distil and distil-build to ubuntu 

### ISSUE THREAD

**Issue by cdbethune** [uncharted-distil/distil#2239]
Alpine is not an ideal image for interfacing with C code, so we should stop fighting and move to Ubuntu.  Check the TA2 Dockerfile to see what version is standard on D3M.

**Comment by Zac-hills** [comment]
https://app.circleci.com/pipelines/github/uncharted-distil/distil/1707/workflows/b1587c04-aa4d-4c25-bc53-1cbdc6067beb/jobs/5775
All tests passed on new ubuntu image.
