### ISSUE TITLE
Add positive label to problem for search requests

### ISSUE THREAD

**Issue by cdbethune** [uncharted-distil/distil#2361]
Issue #2360 adds client support for supplying a positive label when dealing with binary classification problems.  This needs to be included in the search request sent to the TA2 via the `pos_label` field of the `ProblemPerformanceMetric` struct.

**Comment by YohannParis** [comment]
For reference, the front-end will send the positive label under the property `positiveLabel` in the _SolutionRequestMsg_.
see #2392
