### ISSUE TITLE
Clicking on table row doesn't trigger selection

### ISSUE THREAD

**Issue by cdbethune** [uncharted-distil/distil#2403]
Testing against 196_auto_mpg.  Clicking on a row in the table view should cause the row to highlight in pink, and the facets to highlight associated buckets in pink.  Currently selecting displays a border around the row (at least in chrome), but none of the pink highlight visuals appear.

![image](https://user-images.githubusercontent.com/8959554/112052834-f711f000-8b29-11eb-9a46-5d308cf31d66.png)

**Comment by YohannParis** [comment]
This is not an issue, just the pre-ingested dataset needs to be re-ingested and the docker containers updated.
The feature works fine with an imported dataset.
