### ISSUE TITLE
Result Screen Performance Scaling

### ISSUE THREAD

**Issue by phorne-uncharted** [uncharted-distil/distil#2414]
As more and more models get created, the result screen starts to have performance issues. Once about 30 models exist, the client does around 150 requests whenever the user adds or removes a highlight and it takes a few seconds for the UI to process everything and reflect the desired state. Most the requests are for confidence (& rank) and correctness summaries.

An easy (but long) way to see the problem: select the baseball dataset with position as target and run the model creation 15-20 times. Once done, try to add and remove highlights.

Updates should be made to make sure the result screen can handle an increase in models without suffering performance issues.

**Comment by Zac-hills** [comment]
https://github.com/uncharted-distil/distil/pull/2591
first PR
The next PR will give a UI scaling solution
