### ISSUE TITLE
Missing target labels result in collapsed row

### ISSUE THREAD

**Issue by cdbethune** [uncharted-distil/distil#2594]
With the option to work with semi-supervised data after labelling, we can have the situation where we load a dataset with empty labels, and the rows associated with it are empty, and subsequently collapsed:

![image](https://user-images.githubusercontent.com/8959554/118133357-bc606180-b3ce-11eb-8515-2dfdd366d764.png)

We should set a min height or force some type of label like "<none>" in for empty strings so that the row doesn't completely collapse.

**Comment by phorne-uncharted** [comment]
Should we match the `<none>` label we use in the facet?
