### ISSUE TITLE
Only display confidence when scoring on ROC AUC

### ISSUE THREAD

**Issue by cdbethune** [uncharted-distil/distil#2662]
If the user scores via ROC AUC, the intention is to evaluate the model over a range of threshold values.  In such a case, it is not as meaningful to include the ERROR and PREDICTION facets, as they correspond to a single fixed threshold value, and will often not correspond directly with the computed ROC AUC value.

**Comment by Zac-hills** [comment]
![image](https://user-images.githubusercontent.com/25306965/141359718-5cb0f1b1-2cef-4c93-bcf1-f8bbef0d97e8.png)
