### ISSUE TITLE
Geobounds explode not updating variable summary list

### ISSUE THREAD

**Issue by Zac-hills** [uncharted-distil/distil#2685]
Jun  3 12:11:29 ] [ ERROR ] variable `__geo_coordinates` of type `geobounds` does not support summary
github.com/uncharted-distil/distil/api/model/storage/postgres.(*Storage).createField
	/media/zhills/hdd/distil/api/model/storage/postgres/variable.go:300
github.com/uncharted-distil/distil/api/model/storage/postgres.(*Storage).fetchSummaryData
	/media/zhills/hdd/distil/api/model/storage/postgres/variable.go:122
github.com/uncharted-distil/distil/api/model/storage/postgres.(*Storage).FetchSummary
	/media/zhills/hdd/distil/api/model/storage/postgres/variable.go:149
github.com/uncharted-distil/distil/api/routes.VariableSummaryHandler.func1
	/media/zhills/hdd/distil/api/routes/variable_summaries.go:105
net/http.HandlerFunc.ServeHTTP
	/usr/lib/go-1.13/src/net/http/server.go:2007
goji.io/v3.dispatch.ServeHTTP
	/home/zhills/go/pkg/mod/goji.io/v3@v3.0.0/dispatch.go:17
github.com/uncharted-distil/distil/api/middleware.Gzip.func1
	/media/zhills/hdd/distil/api/middleware/gzip.go:61
net/http.HandlerFunc.ServeHTTP
	/usr/lib/go-1.13/src/net/http/server.go:2007
github.com/uncharted-distil/distil/api/middleware.Log.func1
	/media/zhills/hdd/distil/api/middleware/log_http.go:37
net/http.HandlerFunc.ServeHTTP
	/usr/lib/go-1.13/src/net/http/server.go:2007
goji.io/v3.(*Mux).ServeHTTP
	/home/zhills/go/pkg/mod/goji.io/v3@v3.0.0/mux.go:74
net/http.serverHandler.ServeHTTP
	/usr/lib/go-1.13/src/net/http/server.go:2802
net/http.(*conn).serve
	/usr/lib/go-1.13/src/net/http/server.go:1890
runtime.goexit
	/usr/lib/go-1.13/src/runtime/asm_amd64.s:1357 (api/routes/error.go:39)
![Peek 2021-06-03 12-11](https://user-images.githubusercontent.com/25306965/120677413-0c2dc800-c465-11eb-9152-3b8ced4fa6ec.gif)

**Comment by cdbethune** [comment]
GeoBounds shouldn't support exploding - that is used fro geocoords where they are composed from 2 separate lat / lon columns, or timeseries, where you have timestamp, value, and series ID set.  In both cases, exploding undoes the composition of the field, and returns them to their constituent parts.  GeoBounds are currently stored as a vector with a strict interpretation of contents and are not created from multiple columns of data, and therefore should not support the "explode" option.
