### ISSUE TITLE
Coordinate column errors after join

### ISSUE THREAD

**Issue by cdbethune** [uncharted-distil/distil#2847]
Joined a dataset consisting of rainfall data with tiles at geohash level 5 and a sentinel set with tiles at geohash level 5, with the join taking place on the geographic bounds.  The join worked from a computational standpoint, but coordinate facets weren't displaying properly:

![image](https://user-images.githubusercontent.com/8959554/129118344-defdf308-bef7-428e-92ff-a9f8532e882f.png)

**Comment by Zac-hills** [comment]
This was fixed with a previous PR.
