### ISSUE TITLE
Remote sensing dataset stored in public deleted

### ISSUE THREAD

**Issue by cdbethune** [uncharted-distil/distil#2904]
If I import using the functionality that reads from the public folder, the dataset in public gets deleted after ingest.

**Comment by phorne-uncharted** [comment]
Have you double checked your config and made sure the public folder is only used in the one variable? I have not had that happened to me yet.

**Comment by cdbethune** [comment]
export D3MINPUTDIR=/data/d3m_minmeta/datasets/seed_datasets_current
export D3MOUTPUTDIR=/home/chris/outputs
export D3MSTATICDIR=/data/d3m_minmeta/static_resources
export DATAMART_IMPORT_FOLDER=/home/chris/outputs/import

**Comment by cdbethune** [comment]
`PublicSubFolder` is set to the default value of `public`, which seems to end up being appended to the `$D3MOUTPUTDIR` value.  There is no other explicit mention of public.

**Comment by phorne-uncharted** [comment]
still cant reproduce for whatever reason
