### ISSUE TITLE
Enabled clustering and outlier detection in model result and prediction views

### ISSUE THREAD

**Issue by cdbethune** [uncharted-distil/distil#2975]
Clustering and outlier detection don't properly work with model result and prediction views.  It would be good to enable them, but it requires a change to how they are run.  For the result view, we would need to re-run them on test data only, using the model generated outputs.  For the predictions view, we would need to re-run them on the prediction data including the generated labels / values.

**Comment by cdbethune** [comment]
So for the result view, this is purely a UI issue by the sounds of it.  What has to happen on the back end for predictions?

**Comment by phorne-uncharted** [comment]
I think that requires significantly more thought on what is desired. Are we supposed to just cluster the prediction set regardless of how the source set was clustered? If so, then what value does that have? If not, then does that mean we have to have all the features of the source set and not just the features in the model?
