### ISSUE TITLE
ES variable index misaligned from disk variable

### ISSUE THREAD

**Issue by Zac-hills** [uncharted-distil/distil#3004]
Steps to reproduce:
- Join bofa_moisture and bofa_sentinel
- Add cloud variable in label work flow
- Fit on smaller set of variables in order to predict on locust_tiny ds
- Predict on locust_tiny
- Server should fatal panic with OOR

**Comment by cdbethune** [comment]
I've also been unable to reproduce using the steps originally specified and a few variations.  I think we can close.
