### ISSUE TITLE
Drilldown image not displaying pos/negative icon 

### ISSUE THREAD

**Issue by cdbethune** [uncharted-distil/distil#3043]
If you drilldown to an individual image during labelling and set it to positive / negative, an icon reflecting the label status should appear in the top left corner, like it does in the mosaic and table view.

![image](https://user-images.githubusercontent.com/8959554/139315720-1e45907a-1bdc-42d4-a738-a9af39e0ccae.png)

**Comment by mj3cheun** [comment]
fixed in PR #3047
