### ISSUE TITLE
Selected/Excluded search bar

### ISSUE THREAD

**Issue by cdbethune** [uncharted-distil/distil#428]
The Uncharted search bar should be added to both the selected and excluded tabs in the create models screen.  Its content should reflect the filter state of the active facet, or, if the user has entered a search term, it should act as the filter for the selected table, or set the selection for the exclusion table.  Highlight state of facets should reflect the search content as well.

Its not clear whether or not the search bar is available for general use yet, so we may need to chase down the owner.

Depends on #427 

Example from design slides:

![image](https://user-images.githubusercontent.com/8959554/36225472-c6710a7a-1198-11e8-9ddd-2cea1c0723ae.png)

**Comment by YohannParis** [comment]
This might be covered by LexBar that @karlolsonuc implement.

**Comment by cdbethune** [comment]
Yes, this is now tracked under #2075
