### ISSUE TITLE
Sloth Output Update

### ISSUE THREAD

**Issue by phorne-uncharted** [uncharted-distil/distil#765]
Sloth currently outputs the row index (d3m index?) along with the label (column names "0"). This should be updated to output the input columns and have the label added at the end with the column name supplied.

**Comment by phorne-uncharted** [comment]
from Numa:

```
We can't actually use the `output_labels` parameter since there isn't an actual "problem" that would currently work for this primitive, so I can't query metadata for suggested targets, etc. because in this case, the suggested target wouldn't be `WIDTHBREATH` as defined for the `22_handgeometry` problem. So, `pred_class` would actually be expected (which is coming from `image_analyzer` in the base `unicorn` library).
```

**Comment by cdbethune** [comment]
This has been resolved due to subsequent refactoring of unsupervised primitives on the Yonder side, along with the necessary updates within distil.
