### ISSUE TITLE
Provide visual indicator of feature rank scores

### ISSUE THREAD

**Issue by cdbethune** [uncharted-distil/distil#782]
We currently order features by rank, but don't provide any means to differentiate between their magnitudes.  This can be misleading, as a set: `{a: 0.9, b: 0.8, c: 0.01, d: 0.01}` has a large difference in the rank for features `b` and `c` that is in no way expressed to the user.

**Comment by cdbethune** [comment]
We can do the recommended type tagging pretty quickly.  I guess we try for a threshold of 0.5 initially, and see what that turns into in the UI when applied to different datasets.  We should empirically test that it has no ill effects on model generation by comparing a model generated using only recommended types vs. one that uses all types.  We don't want the user to follow the recommendations and generate a poorer model as a result, although I guess you can make an explainability argument for models with a smaller number of input variables.

**Comment by djonker** [comment]
That's probably more a matter of language in how we talk about it to users and how we label it in the user interface (say in the tooltip or whatever). I agree we should probably not use the word **recommended** for features (or for types for that matter). We could for instance say instead that we are tagging **promising candidate** features [and maybe "likely type(s)" for types.]
