### ISSUE TITLE
Improve dataset search handling of substrings

### ISSUE THREAD

**Issue by cdbethune** [uncharted-distil/distil#905]
Currently if I type `chlorine` in as a search term, I would expect to see the following dataset returned:

`66_chlorineConcentration_dataset_TRAIN`

Instead, I only get a back a datamart set that has `chlorine` in the descriptive text.  My guess is that we don't have substring searching enabled, although I'm sure it once was.  You should be able to turn it on with a min length so that it only kicks in if you have N or more letter in your search term.

**Comment by phorne-uncharted** [comment]
This was fixed as part of distil ingest. The dataset id was not being tokenized and analyzed properly.
