### ISSUE TITLE
No vertical scrollbar in Join Suggestion pane with chrome 69.0.3497.81

### ISSUE THREAD

**Issue by cdbethune** [uncharted-distil/distil#990]
My chrome install was recently updated to 69.0.3497.81.  After this update, the join suggestions panel no longer displays a vertical scrollbar.  Everything lays out properly in Firefox.

**Comment by jryu01** [comment]
Chrome version 69 seems pretty outdated. I'm currently on version 74.0.3729.131 and the scrollbar works fine

**Comment by cdbethune** [comment]
Yup, my laptop (Ubuntu 18 LTS) chrome install wasn't updating as expected.  I forced it to 74 and everything is working fine.
